### PR TITLE
Fix NBS optimistic locking

### LINKED ISSUE #3349: NBS optimistic locking in broken
We use the root hash to optimistically lock...but, we allow flush() which alters the set of tables without changing the root. so multiple writers who only flush can stomp on each other.

### PR DESCRIPTION
**Pull request by cmasone-attic**
Introduce a "lock" hash into NBS manifests to address the bad
interaction between Flush() and optimistic locking. Our original
design didn't include Flush(), which changes the set of tables without
updating the root. Thus... an optimistic locking strategy predicated
on checking the currently-persisted root hash is not robust to
interleaved Flush() calls from multiple clients.

Fixes #3349

### CODE REVIEW

File: go/nbs/dynamo_manifest.go [hunk 1]
```diff
@@ -39,13 +40,14 @@ type ddbsvc interface {
 type dynamoManifest struct {
 	table, db string
 	ddbsvc    ddbsvc
+	lock      addr
```
Comment (cmasone-attic) [inline go/nbs/dynamo_manifest.go]: This is the main thing I hemmed and hawwed about and am still not sure is the right thing. On one hand, the details of this 'lock' hash and how it's calculated and how to check it are totally the concern of the `manifest` implementations. On the other, making it their concern means both `manifest` implementations are now stateful, where before they were stateless, which was nice.

**Comment by cmasone-attic** [comment]
PTAL

File: go/nbs/mmap_table_reader.go [hunk 2]
```diff
@@ -67,6 +67,10 @@ func newMmapTableReader(dir string, h addr, chunkCount uint32, indexCache *index
 		buff, err = unix.Mmap(int(f.Fd()), aligned, int(fi.Size()-aligned), unix.PROT_READ, unix.MAP_SHARED)
 		d.PanicIfError(err)
 		index = parseTableIndex(buff[indexOffset-aligned:])
+
+		if indexCache != nil {
```
Comment (rafael-atticlabs) [inline go/nbs/mmap_table_reader.go]: were we just not ever checking the indexCache for the file case?

File: go/nbs/dynamo_manifest.go (hunk 1 above)
Comment (rafael-atticlabs) [inline go/nbs/dynamo_manifest.go]: Yeah, I don't have a problem with this implementation, but abstractly, AWS share:

1-table file format
2-table naming
3-root hash encoding (20 byte hash).

And differ on 
1-Manifest encoding

The one difference makes sense because we need to optimistically lock on an attribute in Dynamo.

I think it makes sense that both implementations should be required to compute the same logical lock hash given the same root hash and included table hashes.

Comment (rafael-atticlabs) [inline go/nbs/dynamo_manifest.go]: Seperately, I noticed when debugging last night, it appeared as though I watched repeated openings of the same manifest which, each time resulted in a different ordering of the table files. I wondered what that was about. Not because it's wrong, just surprising.

Comment (rafael-atticlabs) [inline go/nbs/dynamo_manifest.go]: Ah. i see the issue you are getting at. The manifests because mutable, where as before they were immutable. Yeah, I think i'd be more comfortable if the lock hash was also owned by the nbs store.

File: go/nbs/dynamo_manifest.go [hunk 3]
```diff
@@ -76,25 +79,28 @@ func validateManifest(item map[string]*dynamodb.AttributeValue) (valid, hasSpecs
...
+		return len(item) == 5, false
 	}
 	return false, false
 }
 
-func (dm dynamoManifest) Update(specs []tableSpec, root, newRoot hash.Hash, writeHook func()) (actual hash.Hash, tableSpecs []tableSpec) {
+func (dm *dynamoManifest) Update(specs []tableSpec, root, newRoot hash.Hash, writeHook func()) (actual hash.Hash, tableSpecs []tableSpec, err error) {
 	tableSpecs = specs
 
+	lock := generateLockHash(newRoot, specs)
```
Comment (rafael-atticlabs) [inline go/nbs/dynamo_manifest.go]: nit: `newLock`

File: go/nbs/mmap_table_reader.go (hunk 2 above)
Comment (cmasone-attic) [inline go/nbs/mmap_table_reader.go]: we were not

File: go/nbs/dynamo_manifest.go (hunk 3 above)
Comment (cmasone-attic) [inline go/nbs/dynamo_manifest.go]: Hm. generally, `newFoo` is, in our code, a function that constructs a thing of type `Foo`. Since `Lock` isn't a type, here, that naming convention seems wrong to me.

Comment (rafael-atticlabs) [inline go/nbs/dynamo_manifest.go]: ok. no biggy. "newRoot" is right there as well, that's why I suggested it.

File: go/nbs/dynamo_manifest.go (hunk 1 above)
Comment (cmasone-attic) [inline go/nbs/dynamo_manifest.go]: re: the different ordering, i've seen that too. I think it's because, in `tableSet.Rebase()`, which we do whenever we open a manifest, we do the following to remove dupes in the set of tables we want to open:
```golang
	// Create a list of tables to open so we can open them in parallel.
	tablesToOpen := map[addr]tableSpec{}
	for _, spec := range specs {
		if _, present := tablesToOpen[spec.name]; !present { // Filter out dups
			tablesToOpen[spec.name] = spec
		}
	}
```
and then we iterate that map. Do you think it's important to fix the ordering? I'm sure we could come up with a way

Comment (rafael-atticlabs) [inline go/nbs/dynamo_manifest.go]: no. it's just a bit smelly. made it hard to debug, but i don't see a concrete problem. mainly because our ordering isn't significant. as long as it isn't causing false lock failures.

**Comment by cmasone-attic** [comment]
ok, PTAL at this before I rebase.

File: go/nbs/dynamo_manifest.go (hunk 3 above)
Comment (cmasone-attic) [inline go/nbs/dynamo_manifest.go]: oh, the variable name! Thought you meant the function name and was quite confused
