### PR TITLE
Make sure that set/map diff has completed before returning from noms log

### LINKED ISSUE #2235: noms log sf-crime crashes
For example:
```
        Error Trace:    
        Error:          Received unexpected error "leveldb: closed"


goroutine 750 [running]:
panic(0x4c0860, 0xc822be8490)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/attic-labs/noms/go/d.panicker.Errorf(0x7238e0, 0x21, 0xc822a8b5c0, 0x3, 0x3)
        /Users/kalman/src/go/src/github.com/attic-labs/noms/go/d/try.go:25 +0x9e
github.com/attic-labs/noms/go/d.(*panicker).Errorf(0x9dc6d8, 0x7238e0, 0x21, 0xc822a8b5c0, 0x3, 0x3)
        <autogenerated>:2 +0xbf
github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert.Fail(0xe441e8, 0x9dc6d8, 0xc822a8b530, 0x2b, 0x0, 0x0, 0x0, 0x1)
        /Users/kalman/src/go/src/github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert/assertions.go:225 +0x5cb
github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert.NoError(0xe441e8, 0x9dc6d8, 0xe40028, 0xc820012db0, 0x0, 0x0, 0x0, 0xc822a11da0)
        /Users/kalman/src/go/src/github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert/assertions.go:839 +0x18e
github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert.(*Assertions).NoError(0xc820012630, 0xe40028, 0xc820012db0, 0x0, 0x0, 0x0, 0x0)
        /Users/kalman/src/go/src/github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert/assertion_forward.go:205 +0x5f
github.com/attic-labs/noms/go/chunks.(*internalLevelDBStore).getByKey(0xc82011a280, 0xc822a11da0, 0x1b, 0x1b, 0x9300ac07bf543247, 0x7098a15a79377a42, 0xf71b285c, 0x0, 0x0, 0x0, ...)
        /Users/kalman/src/go/src/github.com/attic-labs/noms/go/chunks/leveldb_store.go:203 +0x161
github.com/attic-labs/noms/go/chunks.(*LevelDBStore).Get(0xc820116d80, 0x9300ac07bf543247, 0x7098a15a79377a42, 0xf71b285c, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/kalman/src/go/src/github.com/attic-labs/noms/go/chunks/leveldb_store.go:92 +0x3db
github.com/attic-labs/noms/go/types.(*BatchStoreAdaptor).Get(0xc8201190a0, 0x9300ac07bf543247, 0x7098a15a79377a42, 0xf71b285c, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/kalman/src/go/src/github.com/attic-labs/noms/go/types/batch_store.go:59 +0xa8
github.com/attic-labs/noms/go/types.(*ValueStore).ReadValue(0xc82012f500, 0x9300ac07bf543247, 0x7098a15a79377a42, 0xf71b285c, 0x0, 0x0)
        /Users/kalman/src/go/src/github.com/attic-labs/noms/go/types/value_store.go:82 +0x1a0
github.com/attic-labs/noms/go/types.Ref.TargetValue(0x9300ac07bf543247, 0x7098a15a79377a42, 0xf71b285c, 0x3, 0xc8221c8a40, 0xc820427720, 0xe82628, 0xc82012f500, 0x0, 0x0)
        /Users/kalman/src/go/src/github.com/attic-labs/noms/go/types/ref.go:50 +0x48
github.com/attic-labs/noms/go/types.metaTuple.getChildSequence(0x9300ac07bf543247, 0x7098a15a79377a42, 0xf71b285c, 0x3, 0xc8221c8a40, 0xc820427720, 0x1, 0xe86d60, 0xc82221fec8, 0x0, ...)
        /Users/kalman/src/go/src/github.com/attic-labs/noms/go/types/meta_sequence.go:45 +0xb2
github.com/attic-labs/noms/go/types.metaSequenceObject.getChildSequence(0xc82031d2c0, 0x3, 0x4, 0xc82011b000, 0xe82628, 0xc82012f500, 0x1b8c43, 0x2, 0x0, 0x0)
        /Users/kalman/src/go/src/github.com/attic-labs/noms/go/types/meta_sequence.go:142 +0xb9
github.com/attic-labs/noms/go/types.metaSequenceObject.beginFetchingChildSequences.func2(0x4bce60, 0xc822be82f8, 0x0, 0x0)
        /Users/kalman/src/go/src/github.com/attic-labs/noms/go/types/meta_sequence.go:157 +0x8a
github.com/attic-labs/noms/go/util/orderedparallel.New.func3(0xc820116ae0, 0xc822524c00, 0xc822a11620, 0xc822a97c70)
        /Users/kalman/src/go/src/github.com/attic-labs/noms/go/util/orderedparallel/ordered_parallel.go:53 +0x9f
created by github.com/attic-labs/noms/go/util/orderedparallel.New
        /Users/kalman/src/go/src/github.com/attic-labs/noms/go/util/orderedparallel/ordered_parallel.go:57 +0x2b9
```
There are a few bugs relating to diff which are similar to this.

I've figured out what happens here. In cmd/noms/diff/diff.go we use exceptions for error handling. Unfortunately, we assume that we can range over the diff output, after which diff has completed. This is *not* the case if there is an exception.

I.e. an exception can be thrown which jumps out of the range loop without the channel closing - see https://github.com/attic-labs/noms/blob/master/cmd/noms/diff/diff.go#L101.

This crashes because diff keeps on running and ends up reading from the leveldb database after it closes... or diff freezes, which is even sadder.

The solution is to make sure that diff does complete when the function returns. There are a few ways to do this, in theory:
- introduce a WaitGroup
- recover from errors
- don't use exceptions

I've tried all of these, and it's triggering some other problem where huge diffs (which sf-crime has, since it's a schema change) aren't properly bailing from diff. It's not reading the "stop channel" for some reason, perhaps?

### PR DESCRIPTION
**Pull request by kalman**
This fixes https://github.com/attic-labs/noms/issues/2235 where set/map
diff was still running when noms log has finished, and already closed
its database. Commonly this would crash.

I've removed panic-based control flow to make error handling explicit,
and added a "DiffLeftRight" method to set/map so that noms log completes
ASAP. See the issue for details.

### CODE REVIEW

File: cmd/noms/diff/summary.go [hunk 1]
```diff
@@ -84,7 +84,6 @@ func diffSummaryList(ch chan<- diffSummaryProgress, v1, v2 types.List) {
 	spliceChan := make(chan types.Splice)
 	stopChan := make(chan struct{}, 1) // buffer size of 1, so this won't block if diff already finished
 
-	defer stop(stopChan)
```
Comment (kalman) [inline cmd/noms/diff/summary.go]: The summary algo doesn't actually stop, so there is no point sending to the stop channel.

File: cmd/noms/diff/diff.go [hunk 2]
```diff
@@ -18,231 +23,218 @@ func shouldDescend(v1, v2 types.Value) bool {
...
 	stopChan := make(chan struct{}, 1) // buffer size of 1, so this won't block if diff already finished
 
-	defer stop(stopChan)
 	go func() {
 		v2.Diff(v1, spliceChan, stopChan)
 		close(spliceChan)
 	}()
 
-	wroteHeader := false
+	wroteHdr := false
```
Comment (kalman) [inline cmd/noms/diff/diff.go]: just a nit, `writeHeader` and `wroteHeader` look very similar from a distance.

File: cmd/noms/diff/diff.go [hunk 3]
```diff
@@ -18,231 +23,218 @@ func shouldDescend(v1, v2 types.Value) bool {
...
-			case types.StructKind:
-				diffStructs(w, p, v1.(types.Struct), v2.(types.Struct))
-			default:
-				panic("Unrecognized type in diff function")
-			}
-		} else {
-			line(w, DEL, key, v1)
-			line(w, ADD, key, v2)
+func diff(w io.Writer, p types.Path, key, v1, v2 types.Value) error {
+	if v1.Equals(v2) {
```
Comment (rafael-atticlabs) [inline cmd/noms/diff/diff.go]: better. thx

File: go/types/map.go [hunk 4]
```diff
@@ -59,13 +59,22 @@ func NewStreamingMap(vrw ValueReadWriter, kvs <-chan Value) <-chan Map {
 	return outChan
 }
 
+// Computes the diff from |last| to |s| using "best" algorithm, which balances returning results early vs completing quickly.
```
Comment (rafael-atticlabs) [inline go/types/map.go]: |s| -> |m|

**Comment by rafael-atticlabs** [comment]
lgtm. maybe also have @willhite take a look?

**Comment by kalman** [comment]
@willhite PTAL?

**Comment by willhite** [comment]
LGTM
