### PR TITLE
Go: Add more documentation for List merge.

### LINKED ISSUE #2717: Documentation on merge.ThreeWay for lists seems wrong
```
//  - If we are dealing with a list:
//    - same index is both removed and inserted wrt parent: conflict
//    - same index is inserted wrt parent, but with different values: conflict
```

This doesn't seem right. I thought it does something different now.

### PR DESCRIPTION
**Pull request by cmasone-attic**
Modify the comment in merge/three_way.go to be accurate, add
lengthy discussion of List merge algorithm in three_way_list.go

Fixes #2717

### CODE REVIEW

**Comment by cmasone-attic** [comment]
PTAL

File: go/merge/three_way.go [hunk 1]
```diff
@@ -47,11 +47,12 @@ func newMergeConflict(format string, args ...interface{}) *ErrMergeConflict {
...
 //    - same field is both removed and inserted wrt parent: conflict
 //    - same field is inserted wrt parent, but with different values: conflict
-//  - If we are dealing with a list:
-//    - same index is both removed and inserted wrt parent: conflict
-//    - same index is inserted wrt parent, but with different values: conflict
 //  - If we are dealing with a set:
 //    - `merged` is essentially union(a, b, parent)
+//  - If we are dealing with a list:
+//    - consider modifications in terms of list 'splices'; insertions and removals at a given index. A 'modification' at an index is expressed as a removal and insertion of a new value.
+//    - splice from one candidate operates at OR removes the index at which the other candidate begins its splice: conflict
```
Comment (aboodman) [inline go/merge/three_way.go]: This doesn't really grammar

File: go/merge/three_way_list.go [hunk 2]
```diff
@@ -11,6 +11,53 @@ import (
 	"github.com/attic-labs/noms/go/types"
 )
 
+// Merge rules for List are a bit more complex than Map, Struct, and Set due
```
Comment (aboodman) [inline go/merge/three_way_list.go]: I think we should just put the list merge algorithm in three_way.go so that we can link to the entire merge algorithm in one place in the documentation.

File: go/merge/three_way.go (hunk 1 above)
Comment (cmasone-attic) [inline go/merge/three_way.go]: That's because I accidentally the whole thing.

**Comment by cmasone-attic** [comment]
Ok, how's this?

**Comment by cmasone-attic** [comment]
I believe this reflects your proposed changes. PTAL

File: go/merge/three_way.go [hunk 3]
```diff
@@ -36,25 +36,76 @@ func newMergeConflict(format string, args ...interface{}) *ErrMergeConflict {
...
-//    - same key is inserted wrt parent, but with different values: conflict
-//  - If we are dealing with a struct:
-//    - same field is both removed and inserted wrt parent: conflict
-//    - same field is inserted wrt parent, but with different values: conflict
-//  - If we are dealing with a list:
-//    - same index is both removed and inserted wrt parent: conflict
-//    - same index is inserted wrt parent, but with different values: conflict
-//  - If we are dealing with a set:
-//    - `merged` is essentially union(a, b, parent)
+// ThreeWay
```
Comment (aboodman) [inline go/merge/three_way.go]: Nit: this header will look weird in godoc - remove.
