### PR TITLE
NBS: updateManifest() fails fast if Update is DOOOOOOMED

### LINKED ISSUE #3574: NBS: Don't persist memTable if manifest.Update() is going to fail
Obvs we can only do this by loading the manifest again (slow and expensive) or getting a less-certain answer by querying the in-process manifest cache

### PR DESCRIPTION
**Pull request by cmasone-attic**
If NomsBlockStore can assume that its manifest is a cachingManifest,
it can pre-emptively check to see if someone else in-process has
already moved the manifest forward and, if so, fail early.

Fixes #3574

### CODE REVIEW

**Comment by cmasone-attic** [comment]
PTAL

File: go/nbs/store.go [hunk 1]
```diff
@@ -405,6 +405,18 @@ func (nbs *NomsBlockStore) updateManifest(current, last hash.Hash) error {
 		return errLastRootMismatch
 	}
 
+	if upstream, doomed := nbs.mm.updateWillFail(nbs.manifestLock); doomed {
+		// Pre-emptive optimistic lock failure. Someone else in-process moved to the root, the set of tables, or both out from under us.
```
Comment (rafael-atticlabs) [inline go/nbs/store.go]: maybe lift this into a local `handleOptimisticLockFailure := func() {...}` that can be used below as well?

Comment (cmasone-attic) [inline go/nbs/store.go]: done
