### PR TITLE
First pass at compaction

### LINKED ISSUE #2944: All NBS stores should share the index cache
Thankfully, NBS supports concurrent file access, so it's not wrong (like it was with LDB) to have multiple views on the same store open, but it's wasteful as each view has heated up a bunch of the same memory

### LINKED ISSUE #3132: NBS: compaction
Some databases in prod have already gotten so many commits that the manifest is too big to fit in DynamoDB.

Whoops.

We need some kind of compaction to get unblocked here

### PR DESCRIPTION
**Pull request by cmasone-attic**
The first cut at compaction blocks UpdateRoot() while it compacts n/2
tables down into a single, large table (where n == number of tables
named in the NBS manifest). It then attempts to update the manifest
with one referencing the compacted table, the novel tables from the
client, and the remaining upstream tables that were not compacted.

If the update fails, probably due to an optimistic lock failure, the
client drops the compacted table it just created, pulls in the tables
from the newly-discovered upstream manifest, and tries again.

Known flaws:
- may explode RAM (#3130)
- doesn't handle novel tables > max tables (#3142)
- may handle optimistic-lock-failures suboptimally (#3141)

Fixes #3132

Also, fixes #2944 because doing so simplifies some code.

### CODE REVIEW

**Comment by cmasone-attic** [comment]
PTAL

File: go/nbs/block_store_test.go [hunk 1]
```diff
@@ -197,6 +197,35 @@ func (suite *BlockStoreSuite) TestChunkStoreFlushOptimisticLockFail() {
 	suite.True(suite.store.UpdateRoot(c2.Hash(), suite.store.Root()))
 }
 
+func (suite *BlockStoreSuite) TestCompactOnUpdateRoot() {
+	testMax := 5
```
Comment (rafael-atticlabs) [inline go/nbs/block_store_test.go]: nit: `testMaxTables`

File: go/nbs/table_set.go [hunk 2]
```diff
@@ -5,165 +5,281 @@
...
+	sort.Sort(chunkSourcesByDescendingCount(ns.upstream))
+
+	max := func(a, b int) int {
+		if a > b {
+			return a
+		}
+		return b
+	}
+
+	partition := len(ns.upstream) - max(2, len(ns.upstream)/2)
```
Comment (rafael-atticlabs) [inline go/nbs/table_set.go]: I think the fanciness here in order to avoid allocating a new slice buffer isn't worth it. can you just do the naive thing here that's easy to read. i.e.

```
tablesToCompact := ...
compactedTable := ...
upstream := 
```

File: go/nbs/table_set.go [hunk 3]
```diff
@@ -5,165 +5,281 @@
...
+func (ts tableSet) Compact() (ns tableSet, compactees chunkSources) {
+	ns = tableSet{
+		novel:    make(chunkSources, len(ts.novel)),
+		upstream: make(chunkSources, len(ts.upstream), len(ts.upstream)+1),
+		p:        ts.p,
+		rl:       ts.rl,
+	}
+	copy(ns.novel, ts.novel)
+	copy(ns.upstream, ts.upstream)
+	sort.Sort(chunkSourcesByDescendingCount(ns.upstream))
```
Comment (rafael-atticlabs) [inline go/nbs/table_set.go]: Does it bother you that we go out of our way to *prepend* a new table to the front of the list, but this appears to not only compact the N smallest tables but also reorder the remaining tables by size.

File: go/nbs/table_set.go [hunk 4]
```diff
@@ -5,165 +5,281 @@
...
+	flattened.upstream = append(flattened.upstream, ts.novel...)
+	flattened.upstream = append(flattened.upstream, ts.upstream...)
+	return
+}
+
+// Merge returns a new tableSet holding the novel tables managed by |ts| and
+// those specified by |specs|. Tables in |ts.upstream| that are not referenced
+// by |specs| are returned in |dropped| so that the caller can close() them
+// appropriately.
+func (ts tableSet) Merge(specs []tableSpec) (merged tableSet, dropped chunkSources) {
```
Comment (rafael-atticlabs) [inline go/nbs/table_set.go]: `Rebase`

**Review by ghost — COMMENTED** [review]
In general, lg. Some small stuff...

File: go/nbs/block_store_test.go (hunk 1 above)
Comment (cmasone-attic) [inline go/nbs/block_store_test.go]: dun

File: go/nbs/file_table_persister.go [hunk 5]
```diff
@@ -15,30 +15,36 @@ import (
...
-			defer checkClose(temp)
-			io.Copy(temp, bytes.NewReader(data))
-			tempName = temp.Name()
-		}
-		return tempName, name, chunkCount
-	}()
+	return ftp.toReader(mt.write(haver))
+}
+
+func (ftp fsTablePersister) toReader(name addr, data []byte, chunkCount uint32) chunkSource {
```
Comment (cmasone-attic) [inline go/nbs/file_table_persister.go]: doen

File: go/nbs/store.go [hunk 6]
```diff
@@ -290,13 +304,24 @@ func (nbs *NomsBlockStore) UpdateRoot(current, last hash.Hash) bool {
 		nbs.mt = nil
 	}
 
-	actual, tableNames := nbs.mm.Update(nbs.tables.ToSpecs(), nbs.root, current, nil)
+	candidate := nbs.tables
+	var compactees chunkSources
+	if candidate.Size() > nbs.maxTables {
```
Comment (cmasone-attic) [inline go/nbs/store.go]: No, `Size()` is just returning the number of tables, which is unaffected by compacting a memTable (do we need a different term for this now?). A `tableSet` is immutable; nothing changes the number of tables in a set after it's constructed.

File: go/nbs/store.go [hunk 7]
```diff
@@ -290,13 +304,24 @@ func (nbs *NomsBlockStore) UpdateRoot(current, last hash.Hash) bool {
...
+		candidate, compactees = candidate.Compact() // Compact() must only compact upstream tables
```
Comment (cmasone-attic) [inline go/nbs/store.go]: done

File: go/nbs/store.go [hunk 8]
```diff
@@ -305,7 +330,10 @@ func (nbs *NomsBlockStore) Version() string {
 	return nbs.nomsVersion
 }
 
-func (nbs *NomsBlockStore) Close() (err error) {
+// Close will block and compact nbs.tables if it contains more entries than
```
Comment (cmasone-attic) [inline go/nbs/store.go]: Done

File: go/nbs/table.go [hunk 9]
```diff
@@ -205,6 +205,7 @@ type chunkReader interface {
 	get(h addr) []byte
 	getMany(reqs []getRecord, foundChunks chan *chunks.Chunk, wg *sync.WaitGroup) bool
 	count() uint32
+	data() uint64
```
Comment (cmasone-attic) [inline go/nbs/table.go]: done

File: go/nbs/table_persister.go [hunk 10]
```diff
@@ -4,7 +4,94 @@
...
+	if chunkCount == 0 {
+		return
+	}
+
+	maxSize := maxTableSize(uint64(chunkCount), totalData)
+	buff := make([]byte, maxSize) // This can blow up RAM (BUG 3130)
+	tw := newTableWriter(buff)
+
+	// Use "channel of channels" ordered-concurrency pattern so that chunks from a given table stay together, preserving whatever locality was present in that table.
+	chunkChans := make(chan chan extractRecord)
```
Comment (cmasone-attic) [inline go/nbs/table_persister.go]: I may be understanding the question wrong, but yes, it will load all input tables concurrently (modulo the rate-limiter channel `rl`). We talked about this the other day, and when I told you that it took a while to do a compaction, you pointed this out as an optimization opportinity.

I used the "channel of channels" pattern that I picked up from your readahead to ensure that the chunks from the different tables don't get all mixed up together. That's what the comment above is referring to.

File: go/nbs/table_persister.go [hunk 11]
```diff
@@ -4,7 +4,94 @@
...
+				defer func() { close(c); wg.Done(); <-rl }()
+				rl <- struct{}{}
+				s.extract(InsertOrder, c)
+			}(src, chunks)
+			chunkChans <- chunks
+		}
+		wg.Wait()
+	}()
+
+	for chunks := range chunkChans {
```
Comment (cmasone-attic) [inline go/nbs/table_persister.go]: done

File: go/nbs/table_reader.go [hunk 12]
```diff
@@ -19,6 +19,7 @@ import (
 
 type tableIndex struct {
 	chunkCount        uint32
+	totalData         uint64
```
Comment (cmasone-attic) [inline go/nbs/table_reader.go]: This is `tableIndex`

File: go/nbs/table_set.go (hunk 3 above)
Comment (cmasone-attic) [inline go/nbs/table_set.go]: Well, the Prepending thing was sort of an opportunistic enhancement. I don't know if it actually matters in practice, so it seemed not worth it to maintain it when compacting. It seems like locality within a table is far-and-away more important, and we don't really know what future work we're going to do to maintain that. Given that, it seemed better to just be simple here.

File: go/nbs/table_set.go (hunk 2 above)
Comment (cmasone-attic) [inline go/nbs/table_set.go]: done

File: go/nbs/table_set.go (hunk 4 above)
Comment (cmasone-attic) [inline go/nbs/table_set.go]: done

File: go/nbs/store.go (hunk 6 above)
Comment (rafael-atticlabs) [inline go/nbs/store.go]: I mean because it could turn out that a memory table that is compacting will end up having 0 chunks (all dups), in which case our compactingChunkSource table shouldn't have been counted.

IOW, it seems like this point should synchronize with any memtable compaction that's taking place before continuing.

File: go/nbs/table_persister.go (hunk 10 above)
Comment (rafael-atticlabs) [inline go/nbs/table_persister.go]: cool. i only asked because i got the impression that you weren't going to do that in this patch.

File: go/nbs/table_reader.go (hunk 12 above)
Comment (rafael-atticlabs) [inline go/nbs/table_reader.go]: sorry. table writer.

File: go/nbs/table_set.go (hunk 3 above)
Comment (rafael-atticlabs) [inline go/nbs/table_set.go]: ok

**Review by ghost — APPROVED** [review]
LGTM
