### PR TITLE
Correctly handle HTTP conflict status on updateRoot

### LINKED ISSUE #2699: fb/slurp and flickr/slurp regularly conflicting on demo-server
If you look at the logs you see the following almost every run:

```
Cronic detected failure or error output for the command:
node /home/ec2-user/js/fb/slurp ...

RESULT CODE: 1

ERROR OUTPUT:
[Error: HTTP Error: 409]

STANDARD OUTPUT:
[2K
0% photos of 90 imported...[2K
100% photos of 90 imported...
```

It's either the fb or flickr importer everytime that conflicts. These two are (purposely) running concurrently. They should auto-resolve, right?

### PR DESCRIPTION
**Pull request by cmasone-attic**
The code in fetch.js and http_batch_store.js weren't really
agreeing on how HTTP failures were reported up the stack. Now,
they agree, and this allows HttpBatchStore.updateRoot() to
correctly detect a conflict response and return false.

This means that the merge logic in Database.commit() works right,
now.

Fixes #2699

### CODE REVIEW

**Comment by cmasone-attic** [comment]
PTAL

File: js/noms/src/http-batch-store-test.js [hunk 1]
```diff
@@ -4,11 +4,33 @@
...
+import {suite, test, setup, teardown} from 'mocha';
 import {assert} from 'chai';
+import Hash from './hash.js';
+import {emptyHash} from './hash.js';
 import HttpBatchStore from './http-batch-store.js';
+import mock from 'mock-require';
 
 suite('HttpBatchStore', () => {
+  setup(() => {
+    for (const protocol of ['http', 'https']) {
```
Comment (arv) [inline js/noms/src/http-batch-store-test.js]: This test only uses http afaict.

Comment (cmasone-attic) [inline js/noms/src/http-batch-store-test.js]: true. Fixed

**Comment by aboodman** [comment]
yay
