### PR TITLE
Fix httpChunkStore race between Put/Commit and Close

### LINKED ISSUE #3572: Close, Put and Commit race in httpChunkStore

### PR DESCRIPTION
**Pull request by cmasone-attic**
Fixes #3572

### CODE REVIEW

**Comment by cmasone-attic** [comment]
PTAL

File: go/datas/http_chunk_store.go [hunk 1]
```diff
@@ -355,53 +358,37 @@ func resBodyReader(res *http.Response) (reader io.ReadCloser) {
...
+		p.ExtractChunks(chunkChan)
 		close(chunkChan)
 	}()
 
 	body := buildWriteValueRequest(chunkChan)
-	url := *hcs.host
-	url.Path = httprouter.CleanPath(hcs.host.Path + constants.WriteValuePath)
 	// TODO: Make this accept snappy encoding
-	req := newRequest("POST", hcs.auth, url.String(), body, http.Header{
+	req := newRequest("POST", auth, u.String(), body, http.Header{
```
Comment (rafael-atticlabs) [inline go/datas/http_chunk_store.go]: remove TODO above? don't see much point in accepting snappy encoding response to this request.

Comment (cmasone-attic) [inline go/datas/http_chunk_store.go]: done
