### PR TITLE
Remove some uses of Backoff

### LINKED ISSUE #3520: Audit uses of Backoff
I see at least one that looks correct (backing off when we get a throttle event from s3 or aws), but others now seem a bit fishy. I'm sure this is my fault, but looking at them now, I think maybe I was thinking it was addressing a worry about "liveness" (one writers failing to make progress), but I'm no longer convinced that's the case.

### PR DESCRIPTION
**Pull request by rafael-atticlabs**
Fixes #3520

### CODE REVIEW

**Comment by rafael-atticlabs** [comment]
I think going forward, we should document at the use-site of Backoff what problem we think it's solving.

File: go/nbs/store.go [hunk 1]
```diff
@@ -381,19 +380,12 @@ func (nbs *NomsBlockStore) Commit(current, last hash.Hash) bool {
 		return true
 	}
 
-	b := &backoff.Backoff{
```
Comment (cmasone-attic) [inline go/nbs/store.go]: Should we do something here where we somehow pipe up a backoff error from Dynamo if we get one, and respond appropriately?

Comment (rafael-atticlabs) [inline go/nbs/store.go]: I'm not sure what happens in that case. My impression is that we get transparently throttled. If we also get errors, then it may be reasonable to back off.

https://github.com/attic-labs/noms/issues/3535

Comment (cmasone-attic) [inline go/nbs/store.go]: No, we get back errors saying that we got throttled

Comment (cmasone-attic) [inline go/nbs/store.go]: at least I think so...that definitely happens with batch gets. I thought the same happened with GetItem or whatever

Comment (cmasone-attic) [inline go/nbs/store.go]: Yeah, you can get a "ProvisionedThroughputExceededException"

Comment (rafael-atticlabs) [inline go/nbs/store.go]: Well, i think #3535 is a good place to address that. It was also kind of unfortunate that we'd backoff in the case of getting a manifest-cache oplock failure.
