### PR TITLE
LocalDatabase vends separate validating BatchStore

### LINKED ISSUE #2598: Syncing chi-building-violations failed commit validation
Sadness... (I was testing @ehalpern's magic new sync byte estimation patch),

```
noms sync http://demo.noms.io/cli-tour::chi-building-violations /Users/rafael/noms::chi-building-violations
        Error Trace:    /s)panic: 
	Error:		Attempted to write Value containing Ref to non-existent object.
	Messages:	upr8j2buesom8hl0tbgh1ftabok4mjt1
, contains ref hhqocaa4n9kksjl1qgeiup4ktslgi2tt, which points to a non-existent Value.
 [recovered]
        Error Trace:    
	Error:		Attempted to write Value containing Ref to non-existent object.
	Messages:	upr8j2buesom8hl0tbgh1ftabok4mjt1
, contains ref hhqocaa4n9kksjl1qgeiup4ktslgi2tt, which points to a non-existent Value.
```

the head of chi-building-violations is at: `ee5t6b0lr8g7h8f66chn18s9p4rg7b2c`

### PR DESCRIPTION
**Pull request by cmasone-attic**
This patch modifies LocalDatabase so that it no longer swaps out
its embedded ValueStore during Pull(). The reason it was doing this
is that Pull() injects chunks directly into a Database, without
doing any work on its own to ensure correctness. For LocalDatabase,
WriteValue() performs de-facto validation as it goes, so it does not
need this additional validation in the general case. To address the
former wtithout impacting the latter, we were making LocalDatabase
swap out its ValueStore() during Pull(), replacing it with one that
performs validation.

This led to inconsistencies, seen in issue #2598. Collections read
from the DB _before_ this swap could have weird behavior if they
were modified and written after this swap.

The new code just lazily creates a BatchStore for use during Pull().

Fixes #2598

### CODE REVIEW

**Comment by cmasone-attic** [comment]
PTAL @rafael-atticlabs 
FYI @ehalpern

**Comment by cmasone-attic** [comment]
Jenkins: perf this

File: go/datas/local_database.go [hunk 1]
```diff
@@ -29,36 +30,40 @@ func (ldb *LocalDatabase) GetDataset(datasetID string) Dataset {
...
 }
 
-func (ldb *LocalDatabase) validatingBatchStore() (bs types.BatchStore) {
-	bs = ldb.ValueStore.BatchStore()
-	if !bs.IsValidating() {
-		bs = newLocalBatchStore(ldb.cs)
-		ldb.ValueStore = types.NewValueStore(bs)
-		ldb.rt = bs
+func (ldb *LocalDatabase) validatingBatchStore() types.BatchStore {
+	if ldb.vbs == nil {
```
Comment (rafael-atticlabs) [inline go/datas/local_database.go]: ha. nice.

File: cmd/noms/noms_sync_test.go [hunk 2]
```diff
@@ -78,6 +81,49 @@ func (s *nomsSyncTestSuite) TestSync() {
...
 }
 
+func (s *nomsSyncTestSuite) TestSync_Issue2598() {
+	ldb2dir := path.Join(s.TempDir, "ldb2")
+	defer s.NoError(os.RemoveAll(ldb2dir))
+
+	sourceDB := datas.NewDatabase(chunks.NewLevelDBStore(s.LdbDir, "", 1, false))
+	// Create dataset "src1", which has a lineage of two commits.
+	source1 := sourceDB.GetDataset("src1")
+	source1, err := sourceDB.CommitValue(source1, types.Number(42))
```
Comment (rafael-atticlabs) [inline cmd/noms/noms_sync_test.go]: the new api is nice.

**Review by ghost — APPROVED** [review]
lgtm.
