### PR TITLE
JS: Fix OrderedPutCache for browser

### LINKED ISSUE #2395: JS: browser/put-cache.js isn't implemented (can't write from browser)
I noticed this while playing with noms on vacation and Peter Abrahamson (not sure of github username) reported hitting this in the slack channel.

I hacked it up here: https://github.com/rafael-atticlabs/noms/pull/2/commits/ffa704c62d1d8966baac34cceec069e36578a46d (not sure what's going on with that PR).

I think a memory-based put-cache is fine for now in the browser. @arv, or @cmasone-attic: can you fix this up and land it so that Peter can proceed?

### PR DESCRIPTION
**Pull request by arv**
Fixes #2395

### CODE REVIEW

**Comment by arv** [comment]
@cmasone-attic PTAL

File: js/src/put-cache-test.js [hunk 1]
```diff
@@ -7,82 +7,85 @@
...
-    const chunks = [];
-    await chunkStream(chunk => { chunks.push(chunk); });
-
-    for (let i = 0; i < canned.length; i++) {
-      assert.isTrue(canned[i].hash.equals(chunks[i].hash));
-    }
-
-    await cache.destroy();
-  });
+  for (const OrderedPutCache of [NodeOrderedPutCache, BrowserOrderedPutCache]) {
```
Comment (arv) [inline js/src/put-cache-test.js]: These tests are unchanged. It now runs them on both implementatations.

**Comment by cmasone-attic** [comment]
THis LGTM, but something happened on Jenkins. It looks like the npm installation over there can't find a whole bunch of the required modules or something. Not sure if it's a Jenkins issue or some odd side effect of this patch (likely the former?)
